apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-command-api
  annotations:
    version: v0.0.1
    description: "Takes in command from map-cli, adds an id, then further sends to an interest based workqueue for further handling"
    authors: Mattilsynet Plattform team
spec:
  components:
    - name: map-command-api
      type: component
      properties:
        image: file://./build/map-command-api_s.wasm
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats-core
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
        - type: link
          properties:
            target:
              name: map-jetstream-nats
              config:
                - name: nats-jetstream-config
                  properties:
                    url: "nats://127.0.0.1:4222"
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
    - name: map-jetstream-nats
      type: capability
      properties:
        image: ghcr.io/Mattilsynet/map-nats-jetstream:v0.0.1-pre-21
    - name: nats-core
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
        config:
          - name: nats-core-config
            properties:
              cluster_uris: "nats://127.0.0.1:4222"
              subscriptions: map.apply, map.delete
      traits:
        - type: spreadscalar
          properties:
            replicas: 1
        - type: link
          properties:
            target: map-command-api
            namespace: wasmcloud
            package: messaging
            interfaces: [handler]
