apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: map-command-api
  annotations:
    version: v0.0.1
    description: ''
    wasmcloud.dev/authors: Mattilsynet Plattform team
spec:
  components:
    - name: map-command-api
      type: component
      properties:
        image: ghcr.io/Mattilsynet/map-command-api:v0.0.1-pre2
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: link
          properties:
            target: nats
            namespace: wasmcloud
            package: messaging
            interfaces: [consumer]
        - type: link    
          properties:
            target: map-jetstream-nats
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [jetstream-publish]
            target_config:
              - name: nats-config
                properties:
                  jwt: ""
                  seed: ""
                  url: "nats://localhost:4222"
    - name: map-jetstream-nats
      type: capability
      properties:
        image: ghcr.io/Mattilsynet/map-nats-jetstream:v0.0.1-pre2
    - name: nats
      type: capability
      properties:
        image: ghcr.io/wasmcloud/messaging-nats:canary
      traits:
        - type: spreadscalar
          properties:
            replicas: 1
        - type: link
          properties:
            target: map-command-api
            namespace: mattilsynet
            package: provider-jetstream-nats
            interfaces: [handler]
            source_config:
              - name: map-command-api-subject
                properties:
                  subscriptions: map.apply, map.delete
 
