name = "map-command-api"
language = "tinygo"
type = "component"
version = "0.1.0"

[component]
wit_world = "map-command-api"
wasm_target = "wasm32-wasi-preview2"
destination = "build/map-command-api_s.wasm"
